version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: my-nginx
    image: nginx:forkapi
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/forkapi/static/:ro
      - web_media:/forkapi/media/
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - be
    networks:
      - forkapi

  be:
    build:
      context: .
      dockerfile: Dockerfile
    #      image: mikebgrep/forkapi:latest  # change with mikebgrep/forkapi:arm64 for RaspberryPI
    container_name: forkapi
    env_file:
      - .env
    restart: always
    command: >
        sh -c "chmod +x /scripts/migration.sh && /scripts/migration.sh ${SEED_DEFAULT_DATA} && chmod 660 /forkapi/sql/db.sqlite3 & usermod -g staff www-data & uwsgi --ini uwsgi.ini --chown-socket=www-data:www-data"
    volumes:
      - ./scripts:/scripts
      - data:/forkapi/sql/
      - uwsgi_data:/tmp/uwsgi/
      - web_media:/forkapi/media/
      - web_static:/forkapi/static/
    networks:
      - forkapi

networks:
  forkapi:

volumes:
  data:
  uwsgi_data:
  web_static:
  web_media:
